/**
 * @description       : 
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             : 
 * @last modified on  : 08-06-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   08-09-2021   Ricardy Banks					   Initial Version
 * 
 **/
public class Daily_Claim_JSONResponse {
    public String status;
    public String errorMessage;
    public String prudentInDataStagingId;
}