/** 
 * @description       : Provider_Demographic_JSONResponse  class.
 * @author            : jyothi.gandhamaneni@PrudentRx.com
 * @group             : 
 * @last modified on  : 08-25-2021
 * @last modified by  : Jyothi Gandhamaneni
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   08-25-2021   Jyothi Gandhamaneni			   Initial Version
 * 
 **/
public class Provider_Demographic_JSONResponse {
    public String status;
    public String errorMessage;
    public String prudentInDataStagingId;
}