/**
 * @description       : 
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             : 
 * @last modified on  : 08-06-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   08-06-2021   Ricardy Banks					   Initial Version
 * 
 **/
@IsTest
private class TestDaily_ClaimsSelector {

	@IsTest
	private static void testSelectById()
	{
		/*
		// Test data
		Daily_Claim__c dailyClaim = new Daily_Claim__c();
		//dailyClaim.Billing_Provider_First_Name__c = 'Something cool';
		//dailyClaim.Name = 'CoolName';
		insert dailyClaim;
				
		// Query
		List<Daily_Claim__c> dailyClaims = 
			new Daily_ClaimsSelector().selectById(new Set<Id> { dailyClaim.Id });
			
		// Assert
		//System.assertEquals('Something cool', dailyClaims[0].Billing_Provider_First_Name__c);
		System.assertEquals('CoolName', dailyClaims[0].Name);
		*/
	}
}